name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Dependencies
      run: |
        go get github.com/fatih/color
        go get github.com/yeka/zip
        go get github.com/josephspurrier/goversioninfo
        go get github.com/Binject/debug/pe
        go get github.com/awgh/rawreader

    - name: Build
      run: go build -v ScareCrow.go

    - name: Test
      run: go test -v ScareCrow.go

  create_tag:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Creaete tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          tag_exists_error: false
          message: "Latest release"
